apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/adservice
  - ../../base/cartservice
  - ../../base/checkoutservice
  - ../../base/currencyservice
  - ../../base/emailservice
  - ../../base/frontend
  - ../../base/paymentservice
  - ../../base/productcatalogservice  
  - ../../base/recommendationservice  
  - ../../base/shippingservice  
  - ../../base/shoppingassistantservice  
images:
  - name: adservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/adservice
    newTag: latest

  - name: cartservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/cartservice
    newTag: latest

  - name: checkoutservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/checkoutservice
    newTag: latest

  - name: currencyservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/currencyservice
    newTag: latest

  - name: emailservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/emailservice
    newTag: a18715c13657de473e14d64bf70328037ebf49a0

  - name: frontend
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/frontend
    newTag: latest

  - name: paymentservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/paymentservice
    newTag: latest

  - name: productcatalogservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/productcatalogservice
    newTag: latest

  - name: recommendationservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/recommendationservice
    newTag: fd840458ecb4c95947691c59ef5f16e6fb472dec

  - name: shippingservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/shippingservice
    newTag: latest

  - name: shoppingassistantservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/shoppingassistantservice
    newTag: latest
