apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: adservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/adservice
    newTag: placeholder

  - name: cartservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/cartservice
    newTag: placeholder

  - name: checkoutservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/checkoutservice
    newTag: placeholder

  - name: currencyservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/currencyservice
    newTag: placeholder

  - name: emailservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/emailservice
    newTag: placeholder

  - name: frontend
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/frontend
    newTag: placeholder

  - name: loadgenerator
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/loadgenerator
    newTag: placeholder

  - name: paymentservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/paymentservice
    newTag: placeholder

  - name: productcatalogservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/productcatalogservice
    newTag: placeholder

  - name: recommendationservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/recommendationservice
    newTag: placeholder

  - name: shippingservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/shippingservice
    newTag: placeholder

  - name: shoppingassistantservice
    newName: 184574354202.dkr.ecr.eu-central-1.amazonaws.com/shoppingassistantservice
    newTag: placeholder
