apiVersion: apps/v1
kind: Deployment 
metadata:
  name: productcatalog
spec:
  replicas: 3
  selector:
    matchLabels:
      app: productcatalog
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template: 
    metadata: 
      labels:
        app: productcatalog

    spec:  
      containers:
      - name: adservice-pod
        image: deaddeal96/productcatalogservice:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3550
        env:
        - name: PORT
          value: "3550"
        - name: DISABLE_PROFILER
          value: "1"
        - name: ENABLE_TRACING
          value: "0"
---
apiVersion: v1
kind: Service
metadata: 
  name: productcatalog-service
spec:
  selector:
    app: productcatalog
  ports:
    - protocol: TCP
      port: 3550
      targetPort: 3550 