apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: google-microservices
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mofayad96/google-microservicesDemo-devops-
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: google-microservices
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfheal: true
      prune: true  
    