apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommendationservice
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/mofayad96/google-microservicesDemo-devops-.git
    targetRevision: main
    path: k8s/recommendationservice

  destination:
    server: https://kubernetes.default.svc
    namespace: google-microservices

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
