name: reusable build 

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
      service_path:
        required: true
        type: string

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # login to aws using access key id , secret access key
      - name: aws configure
        uses: aws-actions/configure-aws-credentials@v4
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{ secrets.AWS_REGION }}
      # that step allow workflow to pull , push docker images to ecr
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      # build docker image with service path, docker file of service , tag the most recent image with latest , sha
      - name: Build and push Docker images
        uses: aws-actions/amazon-ecr-build-and-push-image@v2
        with:
          context: ${{ inputs.service_path }}
          file: ${{ inputs.service_path }}/Dockerfile
          push: true
          
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.service_name }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ inputs.service_name }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: scan docker images with trivy
        uses: aquasecurity/trivy-action@master
        with: 
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ inputs.service_name }}:${{ github.sha }}'
          format: 'table'
          severity: 'CRITICAL'
          exit-code: '0'
          output: 'trivy-report-${{ inputs.service_name }}.txt'
      
      - name: Upload trivy scan results
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: trivy-report-${{ inputs.service_name }}
          path: trivy-report-${{ inputs.service_name }}.txt

      - name: Notify Slack
        if: always()
        uses: slackapi/slack-github-action@v1.27.0
        with:
          payload: |
            {
              "text": "${{ job.status == 'success' && '✅' || '❌' }} *Build ${{ job.status }}: ${{ inputs.service_name }}*\n*Repo:* ${{ github.repository }} | *Branch:* ${{ github.ref_name }}\n<${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Build Logs>"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
        